UAS_OOP-main/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("register/", views.Register.as_view(), name="register")
]

UAS_OOP-main/blogs/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required
from . import views

app_name = "blogs"

urlpatterns = [
    path("create/comment/", login_required(views.CreateComment.as_view()), name="create_comment"),
    path("create/reply/", login_required(views.CreateReply.as_view()), name="create_reply"),
    path("create/bookmark/", login_required(views.CreateBookmark.as_view()), name="create_bookmark"),
    path("create/like/", login_required(views.CreateLike.as_view()), name="create_like"),
    path("<slug:slug>/", views.BlogView.as_view(), name="blog"),
]

UAS_OOP-main/djcms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("accounts/", include("accounts.urls")),
    path("blogs/", include("blogs.urls")),
    path("manage/", include("management.urls")),

    path("", views.Index.as_view(), name="index"),
    path("trendings/", views.Trendings.as_view(), name="trendings"),
    path("latest/", views.Latest.as_view(), name="latest"),
    path("popular/", views.Popular.as_view(), name="popular"),
    path("search/", views.Search.as_view(), name="search"),
    path("bookmark/", views.BookmarkView.as_view(), name="bookmark"),
    path("terms-and-conditions/", views.TermsAndConditions.as_view(), name="terms_and_conditions"),
    path("category/", views.CategoryView.as_view(), name="category"),
    path("category/<slug:cat>/", views.GetCategory.as_view(), name="get_category"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UAS_OOP-main/management/urls.py
from django.urls import path
from . import views

app_name = "manage"

urlpatterns = [
    path("blog/", views.ManageBlog.as_view(), name="blog"),
    path("category/", views.ManageCategory.as_view(), name="category"),
    path("comment/", views.ManageComment.as_view(), name="comment"),

    path("create/blog/", views.CreateBlog.as_view(), name="create_blog"),
    path("create/category/", views.CreateCategory.as_view(), name="create_category"),

    path("delete/blog/<int:id>/", views.DeleteBlog.as_view(), name="delete_blog"),
    path("delete/category/<int:id>", views.DeleteCategory.as_view(), name="delete_category"),
    path("delete/comment/<int:id>", views.DeleteComment.as_view(), name="delete_comment"),

    path("edit/blog/<int:id>/", views.EditBlog.as_view(), name="edit_blog"),
    path("edit/category/<int:id>", views.EditCategory.as_view(), name="edit_category"),
]

UAS_OOP-main/templates/bookmark.html
{% extends 'layout.html' %}

{% block title %}Bookmarks{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mt-3 mb-3">
      Penanda Buku
    </h1>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for bookmark in bookmarks %}
      {% if bookmark.blog.is_active %}
        {% include 'card.html' with blog=bookmark.blog %}
      {% endif %}
    {% empty %}
      </div>
      <div class="row mt-5">
        <p class="text-center">
          Tidak ada Penanda Buku !!!
        </p>
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=bookmarks %}
</div>
{% endblock %}

UAS_OOP-main/templates/card.html
<div class="col">
  <div class="card h-100">
    <div class="ratio ratio-16x9">
      <img src="{{ blog.thumbnail.url }}" class="card-img-top" alt="blog's thumbnail">
    </div>
    <div class="card-body">
      <h5 class="card-title">{{ blog.title }}</h5>
      <p class="card-text">{{ blog.desc|truncatechars:100 }}</p>
    </div>
    <div class="row justify-content-evenly mb-1">
      <div class="col-4">
        <p class="text-muted float-start">
          <i class="bi bi-eye"></i>
          {{ blog.views }}
        </p>
      </div>
      <div class="col-6">
        <p class="text-muted float-end">
          <i class="bi bi-clock-history"></i>
          {{ blog.published_on|timesince }}
        </p>
      </div>
    </div>
    <a class="btn btn-outline-primary w-100" href="{% url 'blogs:blog' blog.slug %}" role="button">Baca selengkapnya -></a>
  </div>
</div>

UAS_OOP-main/templates/category.html
{% extends 'layout.html' %}

{% block title %}Latest{% endblock %}

{% block body %}
{% endblock %}

UAS_OOP-main/templates/get_category.html
{% extends 'layout.html' %}

{% block title %}Latest{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row mb-5">
    <h2 class="text-center">{{ category.category }}</h2>
    <p>{{ category.desc }}</p>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in category.blogs.all %}
      {% if blog.is_active %}
        {% include "card.html" with blog=blog %}
      {% endif %}
    {% empty %}
      <p class="text-center">Tidak ada blog yang ditemukan !!!</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

UAS_OOP-main/templates/index.html
{% extends 'layout.html' %}

{% block title %}Index{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row mb-1">
    <div class="col-6">
      <h2>Tulisan Terbaru</h2>
    </div>
    <div class="col-6">
      <a class="btn btn-primary float-end" href="{% url 'latest' %}" role="button">
        <i class="bi bi-list-check"></i>
        Lihat Semua
      </a>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in latest %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>

  <br><hr>

  <div class="row mb-1">
    <div class="col-6">
      <h2>Postingan Populer</h2>
    </div>
    <div class="col-6">
      <a class="btn btn-primary float-end" href="{% url 'popular' %}" role="button">
        <i class="bi bi-list-check"></i>
        Lihat semua
      </a>
    </div>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in popular %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>
</div>
{% endblock %}

UAS_OOP-main/templates/latest.html
{% extends 'layout.html' %}

{% block title %}Latest{% endblock %}

{% block body %}
<div class="container mt-5 mb-5">
  <div class="row">
    <h1 class="text-center mt-3 mb-3">
      Terbaru
    </h1>
  </div>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    {% for blog in blogs %}
      {% include 'card.html' with blog=blog %}
    {% endfor %}
  </div>
  {% include 'pagination.html' with blogs=blogs %}
</div>
{% endblock %}

UAS_OOP-main/templates/layout.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
<head>
  {% load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <meta property="og:title" content="{% block ogtitle %}DJCMS: Content Management System{% endblock %}">
  <meta property="og:image" itemprop="image" content="{{ SITE_URL }}{% block ogimage %}{% static 'img/og.png' %}{% endblock %}">
  <meta property="og:description" content="{% block ogdescription %}A Blog Management Site aims to view/create/edit/delete blogs.{% endblock %}">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
  <title>{% block title %}{% endblock %} | RESEP MAKANAN</title>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static 'img/aku.jpeg' %}" alt="Logo" width="30" height="30" class="d-inline-block align-text-top">
      RESEP MAKANAN
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'latest' %}">
            <i class="bi bi-stars"></i>
            Terbaru
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'popular' %}">
            <i class="bi bi-graph-up-arrow"></i>
            Populer
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'trendings' %}">
            <i class="bi bi-fire"></i>
            Trending
          </a>
        </li>
        <form class="d-flex" role="search" action="{% url 'search' %}" method="get">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
          <button class="btn btn-success" type="submit">
            <i class="bi bi-search"></i>
          </button>
        </form>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'bookmark' %}">
            <i class="bi bi-bookmarks"></i>
            Penanda Buku
          </a>
        </li>
        {% if request.user.is_author %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-sliders"></i>
            Mengelola
          </a>
          <ul class="dropdown-menu">
            <li>
              <a class="dropdown-item" href="{% url 'manage:blog' %}">
                <i class="bi bi-book"></i>
                Resep
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'manage:category' %}">
                <i class="bi bi-grid"></i>
                Kategori
              </a>
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'manage:comment' %}">
                <i class="bi bi-chat-left-text"></i>
                Komen
              </a>
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">
            <i class="bi bi-box-arrow-right"></i>
            Keluar
          </a>
        </li>
      </ul>
      {% else %}
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">
            <i class="bi bi-box-arrow-in-right"></i>
            Gabung
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'accounts:register' %}">
              <i class="bi bi-person-add"></i>
              Daftar
          </a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

<!-- Messages -->
<div class="container mt-3" id="msg-box">
  {% if messages %}
  {% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
    <strong>{{ message.tags|upper }}</strong> {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endfor %}
  {% endif %}
</div>

{% block body %}{% endblock %}

  
<br><br><br><br><br><br>
<!-- Footer -->
<section>
  <footer class="text-center text-white">
    {% if request.user.is_anonymous %}
    <div class="container p-4 pb-0">
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Daftar gratis</span>
          <a class="btn btn-outline-light btn-rounded" href="{% url 'accounts:register' %}" role="button">Daftar</a>
        </p>
      </section>
    </div>
    {% endif %}
    <div class="text-center p-3 copyright-text">
      © 2023 Copyright:
      <a class="text-white" href="/">Resep Makanan</a>
    </div>
  </footer>
</section>

<!-- Javascripts -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

UAS_OOP-main/templates/pagination.html
<div class="row mt-5 mb-3 justify-content-center">
  <p class="text-center">Page {{ blogs.number }} of {{ blogs.paginator.num_pages }}</p>
</div>
<div class="row">
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      {% if blogs.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% if query %}query={{query}}&{% endif %}page={{ blogs.previous_page_number }}" aria-label="Previous">
            <i class="bi bi-caret-left"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <i class="page-link bi bi-caret-left"></i>
        </li>
      {% endif %}
      {% for i in blogs.paginator.page_range %}
        {% if blogs.number == i %}
          <li class="page-item active" aria-current="page">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% if query %}query={{query}}&{% endif %}page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if blogs.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% if query %}query={{query}}&{% endif %}page={{ blogs.next_page_number }}" aria-label="Next">
            <i class="bi bi-caret-right"></i>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <i class="page-link bi bi-caret-right"></i>
        </li>
      {% endif %}
    </ul>
  </nav>
</div>